### ISSUE TITLE
Instructions could be clearer for IIB on Cloud

### ISSUE THREAD

**Issue by peterbroadhurst** [ot4i/iib-app-connect-trigger-pattern#4]
Would be good to update the instructions to make it clear the https scheme and port to use in the YAML for IIB on Cloud. Most importantly the docs fail to mention the scheme _must_ be changed for IIB on Cloud to https.

See this forum post for detail:
See https://developer.ibm.com/answers/questions/265188/trying-to-create-a-custom-application-in-app-conne/

My reading of the current docs suggest if a port is not specified, then port 7800 would be used by App Connect when performing the registration. That needs to be clarified, because when connecting to IIB on Cloud it doesn't seem ":443" is needed in the host.

**Comment by bthomps** [comment]
Thanks Peter.  Fixed by Matt Bailey: https://github.com/ot4i/iib-app-connect-trigger-pattern/commit/a9060abf9288821aad2f2451306a6c20878c91af
